#!/usr/bin/env python
import sys
import os
import yaml


root_dir = sys.argv[1]
temp_dir = os.path.join(root_dir, "tmp")
os.mkdir(temp_dir)
conf_dir = os.path.join(root_dir, "etc")
os.mkdir(conf_dir)
salt_cfg = os.path.join(conf_dir, "minion")

config = {
    "id": "salt-nox",
    "file_client": "local",
    "fileserver_ignoresymlinks": True,
    "cache_jobs": False,
    "grains": {
        "deployment": "github",
    },
    "root_dir": root_dir,
    "file_roots": {
        "base": [os.getcwd()],
    },
    "states_dirs": [os.getcwd()],
    "cachedir": temp_dir,
}

with open(salt_cfg, "w", encoding="utf-8") as file:
    yaml.dump(config, file)

print("Local Salt Config:")
print(yaml.dump(config))
