name: Unit Testing

on: ["pull_request"]

jobs:
  CentOS7:
    # UnicodeEncodeError: 'ascii' codec can't encode characters in position 98-102: ordinal not in range(128)
    if: false
    strategy:
      matrix:
        salt-version: ["3002.6", "3003"]
    runs-on: ubuntu-latest
    container: centos:7
    steps:
      # We have to find a solution to actions/checkout on CentOS6 (since it wont work there)
      - uses: actions/checkout@v2
      - name: Prep OS
        run: |
          rm -rf ~/.cache
          yum install -y curl
          yum install -y python3-devel
          yum install -y python3-wheel
          yum install -y python3-pip
          python3 --version
          python3 -m ensurepip --default-pip
          python3 -m pip install --user --upgrade pip
          python3 -m pip install --user nox
      - run: python3 -m nox -s "pull_request(salt='${{ matrix.salt-version }}')"
  Debian:
    strategy:
      matrix:
        os-release: ['stable']
        py-version: ['3.7']
        salt-version: ["3001.7", "3002.6", "3003"]
    runs-on: ubuntu-latest
    container: debian:${{ matrix.os-release }}
    steps:
      - uses: actions/checkout@v2
      - name: Prep OS
        run: |
          apt-get -y update || :
          apt-get -y install curl
          apt-get -y install python3-pip || apt-get install python-pip
          apt-get -y install python3 || apt-get install python
          apt-get -y install python${{ matrix.py-version }}
          python3 --version
          python3 -m pip install --user --upgrade pip
          python3 -m pip install --user nox
      - run: python3 -m nox -s "pull_request(salt='${{ matrix.salt-version }}')"
  FreeBSD:
    strategy:
      matrix:
        py-version: ['3.6', '3.7', '3.8']
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo MATRIX_PY_VERSION="$(echo ${{ matrix.py-version }}|tr -d '.')" >> "${GITHUB_ENV}"
      - uses: vmactions/freebsd-vm@v0.1.4
        with:
          usesh: true
          prepare: |
            pkg install -y curl
            pkg install -y "python${{ env.MATRIX_PY_VERSION }}"
            python${{ matrix.py-version }} -m ensurepip --default-pip --user
            python${{ matrix.py-version }} -m pip install --upgrade --user pip
            python${{ matrix.py-version }} -m pip install nox
            echo "Installing Salt"
            curl -o bootstrap.sh -L http://bootstrap.saltproject.io
            sh ./bootstrap.sh -X -P stable
          run: |
            salt-call --versions-report
            python${{ matrix.py-version }} -m nox -s "pull_request(salt=None)"
  OpenSUSE:
    if: false # OpenSuSE's python is too old
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os-release: ['15', '42']
        salt-version: ["3001.7", "3002.6", "3003"]
    container: opensuse/leap:${{ matrix.os-release }}
    steps:
      - name: Prep OS
        run: |
          zypper install -y tar gzip xz curl
          zypper install -y python3
          zypper install -y python3-pip
          python3 -m pip install --user --upgrade pip
          python3 -m pip install --user nox
      - uses: actions/checkout@v2 # Must come after Prep OS on OpenSUSE
      - name: Install Salt
        run: |
          curl -o bootstrap.sh -L http://bootstrap.saltproject.io
          sh ./bootstrap.sh -X -P stable ${{ matrix.salt-version }}
      - run: python3 -m nox -s "pull_request(salt=None)"
  MacOS:
    # ERROR: Could not find a version that satisfies the requirement pyobjc-framework-searchkit==6.2.2 (from salt)
    # ERROR: No matching distribution found for pyobjc-framework-searchkit==6.2.2
    if: false
    strategy:
      matrix:
        os-release: ['10.15']
        py-version: ['3.5', '3.6', '3.7', '3.8']
        salt-version: ["3001.7", "3002.6", "3003"]
    runs-on: macos-${{ matrix.os-release }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py-version }}
      - name: Prep OS
        run: |
          python -m pip install --user --upgrade pip
          python -m pip install --user nox
      - name: Install Salt
        run: |
          curl -o bootstrap.sh -L http://bootstrap.saltproject.io
          sh ./bootstrap.sh -X -P stable ${{ matrix.salt-version }}
      - run: python -m nox -s "pull_request(salt=none)"
  Ubuntu:
    strategy:
      matrix:
        os-release: ['18.04', '20.04']
        py-version: ['3.5', '3.6', '3.7', '3.8']
        salt-version: ["3001.7", "3002.6", "3003"]
    runs-on: ubuntu-${{ matrix.os-release }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py-version }}
      - name: Prep OS
        run: |
          sudo apt-get -y update || :
          sudo apt-get -y install curl
          python3 -m pip install --user --upgrade pip
          python3 -m pip install --user nox
      - run: python3 -m nox -s "pull_request(salt='${{ matrix.salt-version }}')"
  Windows:
    strategy:
      matrix:
        os-release: ['2016', '2019']
        py-version: ['3.5', '3.6', '3.7', '3.8']
        salt-version: ["3001.7", "3002.6", "3003"]
    runs-on: windows-${{ matrix.os-release }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py-version }}
      - name: Prep OS
        run: |
          python -m pip install --user --upgrade pip
          python -m pip install --user nox
      - name: Install Salt
        run: |
          Invoke-WebRequest -Uri https://winbootstrap.saltproject.io -OutFile C:\Temp\bootstrap-salt.ps1
          Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope CurrentUser
          C:\Temp\bootstrap-salt.ps1 -runservice false -pythonVersion 3 -version ${{ matrix.salt-version }}
          Set-ExecutionPolicy -ExecutionPolicy Undefined -Scope CurrentUser
          echo "C:\salt" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - run: |
          dir
          salt-call --versions-report
          python3 -m nox -s "pull_request(salt=None)"
